// <auto-generated />
using System;
using CombineQueries.Infra.Repos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CombineQueries.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260909172741_DemoCartsSeed")]
    partial class DemoCartsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Account.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61742182-1a33-460e-bf32-38344c41958c"),
                            Active = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "CombineQueries alpha",
                            Name = "world",
                            Token = "p1hfc9m8vzjgrstd",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Chain", b =>
                {
                    b.Property<Guid>("TranslatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("TranslatorId", "Id");

                    b.HasIndex("TranslatorId", "ParentId");

                    b.ToTable("Chains", (string)null);
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Hyper", b =>
                {
                    b.Property<Guid>("TranslatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("TranslatorId", "Id");

                    b.HasIndex("TranslatorId", "Url")
                        .IsUnique();

                    b.ToTable("Hypers", (string)null);
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Translator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alphabet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseForwardUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Alphabet")
                        .IsUnique();

                    b.ToTable("Translators");
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.VirtualFragment", b =>
                {
                    b.Property<Guid>("TranslatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("End")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Jump")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TranslatorId", "Id");

                    b.HasIndex("TranslatorId", "Level");

                    b.HasIndex("TranslatorId", "Text")
                        .IsUnique();

                    b.ToTable("VirtualFragments", (string)null);
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Chain", b =>
                {
                    b.HasOne("CombineQueries.Domain.Aggregates.Translator.Translator", null)
                        .WithMany("Chains")
                        .HasForeignKey("TranslatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Hyper", b =>
                {
                    b.HasOne("CombineQueries.Domain.Aggregates.Translator.Translator", null)
                        .WithMany("Hypers")
                        .HasForeignKey("TranslatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.VirtualFragment", b =>
                {
                    b.HasOne("CombineQueries.Domain.Aggregates.Translator.Translator", null)
                        .WithMany("VirtualFragments")
                        .HasForeignKey("TranslatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombineQueries.Domain.Aggregates.Translator.Translator", b =>
                {
                    b.Navigation("Chains");

                    b.Navigation("Hypers");

                    b.Navigation("VirtualFragments");
                });
#pragma warning restore 612, 618
        }
    }
}
